package ro.licence.cristian.business.dto.websocket_dto.enums;

public enum EventType {
    MARKER_USER_CREATED,
    MARKER_USER_UPDATED,
    MARKER_USER_DELETED,
    MARKER_EVENT_CREATED,
    MARKER_EVENT_UPDATED,
    MARKER_EVENT_DELETED,
    NOTIFICATION,
    NOTIFICATION_NEW_EVENT,
    CHAT_MESSAGE,
    CHAT_ROOM_NEW_PARTICIPANT,
    CHAT_ROOM_PARTICIPANT_LEFT,
    CHAT_ROOM_MESSAGE,
    CHAT_ROOM_TYPING,
    CHAT_ROOM_TYPING_STOP,
    TYPING,
    TYPING_STOP
}
