export class EventType {
  static MARKER_USER_CREATED = 'MARKER_USER_CREATED';
  static MARKER_USER_UPDATED = 'MARKER_USER_UPDATED';
  static MARKER_USER_DELETED = 'MARKER_USER_DELETED';
  static MARKER_EVENT_CREATED = 'MARKER_EVENT_CREATED';
  static MARKER_EVENT_UPDATED = 'MARKER_EVENT_UPDATED';
  static MARKER_EVENT_DELETED = 'MARKER_EVENT_DELETED';
  static NOTIFICATION = 'NOTIFICATION';
  static NOTIFICATION_NEW_EVENT = 'NOTIFICATION_NEW_EVENT';
  static CHAT_MESSAGE = 'CHAT_MESSAGE';
  static CHAT_ROOM_NEW_PARTICIPANT = 'CHAT_ROOM_NEW_PARTICIPANT';
  static CHAT_ROOM_PARTICIPANT_LEFT = 'CHAT_ROOM_PARTICIPANT_LEFT';
  static CHAT_ROOM_MESSAGE = 'CHAT_ROOM_MESSAGE';
  static TYPING = 'TYPING';
  static TYPING_STOP = 'TYPING_STOP';
  static CHAT_ROOM_TYPING = 'CHAT_ROOM_TYPING';
  static CHAT_ROOM_TYPING_STOP = 'CHAT_ROOM_TYPING_STOP';
}
